# Generated by Django 3.0.7 on 2020-07-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegPeep2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnrollmentNo', models.IntegerField()),
                ('Branch', models.CharField(max_length=50)),
                ('YearofStudy', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'RegiPeep2',
            },
        ),
        migrations.CreateModel(
            name='RegPeep3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I_SubjectCode', models.CharField(max_length=50)),
                ('II_SubjectCode', models.CharField(max_length=50)),
                ('III_SubjectCode', models.CharField(max_length=50)),
                ('IV_SubjectCode', models.CharField(max_length=50)),
                ('V_SubjectCode', models.CharField(max_length=50)),
                ('VI_SubjectCode', models.CharField(max_length=50)),
                ('VII_SubjectCode', models.CharField(max_length=50)),
                ('VIII_SubjectCode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'RegiPeep3',
            },
        ),
        migrations.CreateModel(
            name='RegPeep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailId', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('PhoneNo', models.IntegerField()),
                ('regpeep2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igem.RegPeep2')),
                ('regpeep3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igem.RegPeep3')),
            ],
            options={
                'db_table': 'RegiPeep',
            },
        ),
    ]
