# Generated by Django 3.0.7 on 2020-07-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regpeep',
            name='regpeep2',
        ),
        migrations.RemoveField(
            model_name='regpeep',
            name='regpeep3',
        ),
        migrations.AddField(
            model_name='regpeep2',
            name='regpeep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='igem.RegPeep'),
        ),
        migrations.AddField(
            model_name='regpeep3',
            name='regpeep2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='igem.RegPeep2'),
        ),
        migrations.AlterField(
            model_name='regpeep2',
            name='Branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='regpeep2',
            name='EnrollmentNo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='regpeep2',
            name='YearofStudy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='regpeep3',
            name='III_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='regpeep3',
            name='II_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='regpeep3',
            name='IV_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='regpeep3',
            name='I_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='regpeep3',
            name='VIII_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='regpeep3',
            name='VII_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='regpeep3',
            name='VI_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='regpeep3',
            name='V_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
