# Generated by Django 3.0.7 on 2020-07-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igem', '0002_auto_20200709_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regpeep',
            name='EmailId',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='regpeep',
            name='Password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='regpeep',
            name='PhoneNo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='regpeep',
            name='Username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
