# Generated by Django 3.0.7 on 2020-07-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igem', '0003_auto_20200709_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regpeep2',
            name='regpeep',
        ),
        migrations.RemoveField(
            model_name='regpeep3',
            name='regpeep2',
        ),
        migrations.AddField(
            model_name='regpeep',
            name='regpeep2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='igem.RegPeep2'),
        ),
        migrations.AddField(
            model_name='regpeep',
            name='regpeep3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='igem.RegPeep3'),
        ),
    ]
