# Generated by Django 3.0.7 on 2020-07-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igem', '0004_auto_20200710_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regpeep',
            name='regpeep2',
        ),
        migrations.RemoveField(
            model_name='regpeep',
            name='regpeep3',
        ),
        migrations.AddField(
            model_name='regpeep',
            name='Branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='regpeep',
            name='EnrollmentNo',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='regpeep',
            name='III_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='regpeep',
            name='II_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='regpeep',
            name='IV_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='regpeep',
            name='I_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='regpeep',
            name='VIII_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='regpeep',
            name='VII_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='regpeep',
            name='VI_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='regpeep',
            name='V_SubjectCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='regpeep',
            name='YearofStudy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='RegPeep2',
        ),
        migrations.DeleteModel(
            name='RegPeep3',
        ),
    ]
