# Generated by Django 3.0.8 on 2020-07-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igem', '0010_auto_20200717_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfolder',
            name='File_to_upload',
            field=models.FileField(blank=True, null=True, upload_to='coursemat/media/'),
        ),
    ]
