# Generated by Django 3.0.8 on 2020-07-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igem', '0011_auto_20200717_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadfolder',
        ),
    ]
