# Generated by Django 3.0.8 on 2020-07-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igem', '0012_delete_uploadfolder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regpeep',
            old_name='PhoneNo',
            new_name='Gender',
        ),
    ]
